# Makefile

# Compiler
CXX = g++-11

# Compiler flags
CXXFLAGS = -O3 -std=c++17

# Target executable
TARGET = main

# Source file
SRC = main.cpp

# Default target
all: $(TARGET)

# Build target
$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)